### ISSUE TITLE
Please consider to add unit testing

### ISSUE THREAD

**Issue by surrealist** [RevensofT/.Net-Anarchy#2]
While it is ensure code correctness, it will help others as a live example too.

**Comment by surrealist** [comment]
Sorry, I've just see you included an example project in the repo. 
But unit tests are still considering helpful.

**Comment by RevensofT** [comment]
You know, you don't need any permission from me to add or change anything(that what's open source mean to be), if you want anything just fork a project and make it as you want and if you think what's you made it should be merge to master than you pull a request back to master. 
Issue is use for someone want something but they can't make it happen so they leave an issue for other people who can make it happen do it(of course, it must be catch their interest too).

By the way, C# isn't even my second programing language so write it without any error is already miracle for me. :sweat_smile:

**Comment by surrealist** [comment]
:smirk: So, as you said,  I might already understood well about the Issue purposes. You may not think that 1. I'm not understand the code well enough to create unit testings myself. 2. I don't have enough time to do it now and I don't want to forget about it so I created this issue so someone can do it for me. 

BTW, If you think the issue is not related to your repository plan, you can close it na krub.

**Comment by RevensofT** [comment]
Common, don't use it as to do list; I leave it open because it's not conflict with my main purpose, they might be stray from plan but if it still be benefit to main purpose, I welcome all of them. However it's sadly you don't take my bait. :innocent:

**Comment by surrealist** [comment]
Since I had sent pull request #3 and merged already. So I'd like to close this issue. Thanks.
